### PR TITLE
Add a Codacy badge to README.md

### PR DESCRIPTION
**Pull request by codacy-badger**

### CODE REVIEW

**Review by abiodunaremu — COMMENTED** [review]
Codacy badge will be added for up to date project stat

**Review by abiodunaremu — APPROVED** [review]
Pull request from codacy is valid

**Comment by psalmzy** [comment]
awesome

**Review by psalmzy — APPROVED** [review]
adding Codacy badge

**Review by psalmzy — APPROVED** [review]

**Comment by 0m0hsam** [comment]
Adding  Codacy badge

**Review by 0m0hsam — APPROVED** [review]
Okay sir

**Review by 0m0hsam — APPROVED** [review]

**Review by 0m0hsam — APPROVED** [review]
Done

**Review by 0m0hsam — APPROVED** [review]

**Review by psalmzy — APPROVED** [review]
Review Done

**Pull request merged**
